### ISSUE TITLE
Add `/rfd/0123/discussion` route that redirects to GH PR

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/rfd-site#60]
It would just be a loader, no page necessary, and do something similar to the RFD view one, except we would not try to fetch the discussion and we would only redirect if the user has the right perms. If the user is not logged in, we should **always** redirect to login (even for public RFDs).

https://github.com/oxidecomputer/rfd-site/blob/c42214b4cda29f84c8d367d0bcfac60295885b55/app/routes/rfd.%24slug.tsx#L82-L121

**Comment by benjaminleonard** [comment]
Should be pretty easy, can just use the PR number like we do in the dialog. If there isn't a discussion do we 404 or redirect to the RFD?

https://github.com/oxidecomputer/rfd-site/blob/c42214b4cda29f84c8d367d0bcfac60295885b55/app/components/rfd/RfdDiscussionDialog.tsx#L237

**Comment by david-crespo** [comment]
I'd probably 404 since we don't have a nice way of saying "sorry!" on the RFD page if we land there.

**Comment by augustuswm** [comment]
I like this as it means we can probably retire https://{number}.rfd.oxide.computer/discussion , which is handled by some technology that we would like to stop supporting. It also means it is part of our site / api, and not another private thing.
