### ISSUE TITLE
Incorrect rendering of text that is monospace and bold.

### ISSUE THREAD

**Issue by inickles** [oxidecomputer/rfd-site#74]
We have an RFD with Asciidoc similar to the following:

```
`[.black]#*Text*#`
```

which gets rendered similar to `Textstrong>`. Here's the element:

```
<strong>Text<!--<wbr/-->strong&gt;</strong>
```

The issue can reproduced with just, it doesn't also need the highlighting from the original example:

```
`*Text*`
```

**Comment by benjaminleonard** [comment]
Got a PR out for this.

One note – your formatting options inside a code block are going to be limited. We only have one weight of the code font (I might look at adding a bold), and the `.black` class won't do anything.
