### ISSUE TITLE
Some text in Mermaid "packet" diagrams is the same color as the background

### ISSUE THREAD

**Issue by hawkw** [oxidecomputer/rfd-site#81]
Mermaid has a ["packet"](https://mermaid.js.org/syntax/packet.html) diagram type for depicting the layout of network packets and other bitfields. This diagram type places text on top of boxes in the diagram as well as above and below those boxes. For example, see this diagram:

![Image](https://github.com/user-attachments/assets/3fcec019-7fbc-4373-a761-f9b4c1bd7711)

Note that each box has starting and ending bit numbers for the depicted range, above the box. Furthermore, the diagram has a title, in this case "ENA Format 1", below the entire diagram.

Unfortunately, when rendered by the RFD site, all text in the diagram is the same color as the background. This is fine for the labels placed on top of the boxes, because the box background color is different. However, for text placed outside of the boxes, like the bit range numbers and the diagram's title, they are rendered unreadable. For example:
![Image](https://github.com/user-attachments/assets/bb28792e-8ffd-40cd-b21f-47a68200194d)

Note that the labels present in the screenshot from the Mermaid web editor are not visible here. 

If we highlight the entire diagram, we see that the text *is* present, it's just the same color as the page's background, rendering it unreadable:
![Image](https://github.com/user-attachments/assets/1f7fdb39-943c-422e-aa55-597525387222)

**Comment by benjaminleonard** [comment]
Fixed by #82 

I am seeing some strange behaviour where the packet diagram is flashing in and disappearing until toggled again. Will check if still the case on the prod site.

**Comment by hawkw** [comment]
Yay, thanks for fixing this! Looking at RFD 520, it now renders nicely, and I haven't observed any flashing behavior. Will let you know if I do see it.
![Image](https://github.com/user-attachments/assets/2bc54476-4852-43ef-8749-e72b762873dd)
